"""add priorty to task

Revision ID: 196ad7fe59e5
Revises: 321e0dd85928
Create Date: 2026-05-19 15:11:36.845715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "196ad7fe59e5"
down_revision: Union[str, Sequence[str], None] = "321e0dd85928"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("priority", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "priority")
    # ### end Alembic commands ###
